[package]
name = "mx-esdt-creator-meta"
version = "0.0.0"
authors = ["you"]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.mx-esdt-creator]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.41.3"
